# Generated by Django 5.0.6 on 2024-09-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_ram_product_speed_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='speed',
        ),
    ]
